#!/bin/sh
a=$1
b=$2
if [ $a = '--help' ] ; then echo '
	-i : images only(.jpg,.png,.svg)
	-------------------------------
	-s : sound only(.wav,.mp3,.ogg)' ;
else
	if [ $a = '-i' ] ; then 
	grep -o 'https\?://[a-z0-9./]*\.jpg' < $b
	grep -o 'https\?://[a-z0-9./]*\.png' < $b
	grep -o 'https\?://[a-z0-9./]*\.svg' < $b

	else
	if [ $a = '-s' ] ; then 
	grep -o 'https\?://[a-z0-9./]*\.wav' < $b
	grep -o 'https\?://[a-z0-9./]*\.mp3' < $b
	grep -o 'https\?://[a-z0-9./]*\.ogg' < $b

		else
		grep -o 'https\?://[a-z0-9./]*\.png' < $a
		grep -o 'https\?://[a-z0-9./]*\.jpg' < $a
		grep -o 'https\?://[a-z0-9./]*\.svg' < $a
		grep -o 'https\?://[a-z0-9./]*\.wav' < $a
		grep -o 'https\?://[a-z0-9./]*\.mp3' < $a
		grep -o 'https\?://[a-z0-9./]*\.ogg' < $a
fi;fi;fi;
