#!/bin/sh
a=$1
b=$2
if [ $a = '--help' ] ; then echo '
	-i : images only(.jpg,.png,.svg)
	-------------------------------
	-s : sound only(.wav,.mp3,.ogg)' ;
else
	if [ $a = '-i' ] ; then 
	grep -o 'src=[^ ]*.jpg"' < $b | tr -d 'src="'
	grep -o 'src=[^ ]*.png"' < $b | tr -d 'src="'
	grep -o 'src=[^ ]*.svg"' < $b | tr -d 'src="'

	else
	if [ $a = '-s' ] ; then 
	grep -o 'src="[^ ]*\.wav"' < $b | tr -d 'src="'
	grep -o 'src="[^ ]*\.mp3"' < $b | tr -d 'src="'
	grep -o 'src="[^ ]*\.ogg"' < $b | tr -d 'src="'

		else
	grep -o 'src="[^ ]*.ogg"' < $a | tr -d 'src="'
	grep -o 'src="[^ ]*.wav"' < $a | tr -d 'src="'
	grep -o 'src="[^ ]*.mp3"' < $a | tr -d 'src="'
	grep -o 'src="[^ ]*.jpg"' < $a | tr -d 'src="'
	grep -o 'src="[^ ]*.svg"' < $a | tr -d 'src="'
	grep -o 'src="[^ ]*.png"' < $a | tr -d 'src="'
fi;fi;fi;
