#!/bin/sh
a=$1
b=$2
if [ $a = '--help' ] ; then echo '
	-i : images only
	-s : sound only' ;
else
	if [ $a = '-i' ] ; then 
	grep -o 'http://[a-z0-9./]*\.jpg' < $b
	grep -o 'http://[a-z0-9./]*\.png' < $b
	grep -o 'http://[a-z0-9./]*\.svg' < $b

	else
	if [ $a = '-s' ] ; then 
	grep -o 'http://[a-z0-9./]*\.wav' < $b
	grep -o 'http://[a-z0-9./]*\.mp3' < $b
	grep -o 'http://[a-z0-9./]*\.ogg' < $b

		else
		grep -o 'http://[a-z0-9./]*\.png' < $a
		grep -o 'http://[a-z0-9./]*\.jpg' < $a
		grep -o 'http://[a-z0-9./]*\.svg' < $a
		grep -o 'http://[a-z0-9./]*\.wav' < $a
		grep -o 'http://[a-z0-9./]*\.mp3' < $a
		grep -o 'http://[a-z0-9./]*\.ogg' < $a
fi;fi;fi;
