#!/bin/bash
echo "---------------------------------------------------------------------"
echo "Examples while in the same dir as script todo."
echo 'Add records to todolist: ./todo -a "txt"'
echo 'Add 1 record, e.g.: ./todo -a "My first todo record"'
echo 'Add more than 1 records, e.g. for 3: ./todo -a 3 "txt1" "txt2" "txt3"'
echo ""
echo "Display todolist: ./todo -w"
echo ""
echo "Delete records from todolist(k,l=numbers): ./todo -d k,l"
echo "Example - delete second and fifth record: ./todo -d 2,5"
echo "---------------------------------------------------------------------"
