#!/bin/bash
do_help=no
ret_val=0
records=""
touch todolist
tmp_file=$$1
echo_todolist="no"
touch $tmp_file
while [ -n "$1" ] ; do
	case "$1" in
	--help)
		do_help=yes
		break
		;;
	-a)	
		shift
		number_records_add=`echo $1 | grep  "[0-9]"`
		if [ "$number_records_add" != "$1" ] ; then
			number_records_add=1
		fi
		i=0
		while [ $i -lt  $number_records_add ] ; do
			if [[ $i -eq 0 && $number_records_add -gt 1 ]] ; then
				shift
			fi
			if [ $i -gt 0 ] ; then 
				shift
			fi
			record=`echo $1 | grep "^-"`
			if [[ -n "$1"  && -z $record ]] ; then
				echo "$1" >> $tmp_file 
			else
				echo "No record to add found" >&2
				ret_val=1
				break
			fi
			i=$(($i+1))
		done
		;;
	-w)
		echo_todolist="yes"
		;;
	
	*)
		ret_val=2
		break
		;;
	esac
	shift
done
if [ "$do_help" = "yes" ] ; then
	echo "zatim nic"
fi
if [ $ret_val -gt 0 ] ; then
	echo 'type "--help" for help' >&2
	exit $ret_val
fi

cat $tmp_file >> todolist
rm $tmp_file
if [ $echo_todolist = "yes" ] ; then
	cat -n todolist
fi
